include:
  - board: nice_nano_v2
    shield: kyria_left
  - board: nice_nano_v2
    shield: kyria_right
  - board: nice_nano_v2
    shield: settings_reset
  # - board: nice_nano_v2
  #   shield: corne_left
  # - board: nice_nano_v2
  #   shield: corne_right
